
n_outer: 2
n_inner: 2

split_dir: "splits"
score_dir: "scores"
best_dir: "fold_best"

model_families:
    trees:
        RandomForestClassifier:
            n_estimators: [5, 15, 25]
            criterion: ["entropy"]
        #ExtraTreesClassifier:
            #n_estimators: [5, 10, 15]
            #criterion: ["gini", "entropy"]
    
    neighbors:
        KNeighborsClassifier:
            n_neighbors: [1, 2, 3] 
            weights: ["distance"] #["uniform", "distance"]


