
n_outer: 5
n_inner: 5

split_dir: "splits"
score_dir: "scores"
best_dir: "best_models"
summary_file: "nested_cv_summary.json"

model_families:
    trees:
        RandomForestClassifier:
            n_estimators: [5, 15, 30]
            criterion: ["entropy", "gini"]
        ExtraTreesClassifier:
            n_estimators: [5, 15, 30]
            criterion: ["gini", "entropy"]
    
    neighbors:
        KNeighborsClassifier:
            n_neighbors: [1, 2, 3] 
            weights: ["distance", "uniform"]

    svm:
        SVC:
            kernel: ["linear", "rbf", "poly"]
